import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
    title: "Doomi",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className="w-10/12 m-auto">
            {children}
        </div>
    );
}